export default [
    {
        "isCurrencyLeft": 1,
        "title": "Pei Mei Vitamin C Face Serum – Glow-Boosting Elixir for Radiant Skin",
        "itemSoldCnt": 28,
        "itemDiscount": "53%",
        "itemCurrentStock": 12,
        "itemId": 181793809,
        "image": "https://static-01.daraz.com.np/p/39000adcd6aab87baf4f761c157abb97.jpg",
        "itemHaveStock": 1, 
        "price": "165",
        "currency": "Rs.",
        "itemPrice": "350",
        },
      {
        "isCurrencyLeft": 1,
        "title": "3 in 1 100W Fast Charging Data Cable Automatic Switch Off System",
        "itemSoldCnt": 21,
        "itemDiscount": "72%",
        "itemCurrentStock": 9,
        "itemId": 185086588,
        "image": "https://static-01.daraz.com.np/p/9906692e2ce0a1dd3bb39aded3718c77.jpg",
        "itemHaveStock": 1,
        "price": "139",
        "currency": "Rs.",
        "itemPrice": "500",
        },
      {
        "isCurrencyLeft": 1,
        "title":"LCD Writing Tab 8.5 Inch With Pen Writing Pad | Reusable Child Early Learning LCD Writing Tablet | LCD Writing Tablet",
        "itemSoldCnt": 10,
        "itemDiscount": "75%",
        "itemCurrentStock": 4,
        "itemId": 123461942,
        "image": "https://static-01.daraz.com.np/p/6e88a20785bdc65ddbdcb20f4ebd8777.jpg",
        "itemHaveStock": 1,
        "price": "125",
        "currency": "Rs.",
        "itemPrice": "499",
        },
      {
        "isCurrencyLeft": 1,
        "title": "Women Men Waist Trainer Trimmer Sauna Sweat Belt Belly Corsets Control Sport Burner Workout Weight Loss Slimming Body Shaper",
        "itemSoldCnt": 20,
        "itemDiscount": "55%",
        "itemCurrentStock": 20,
        "itemId": 129475727,
        "image": "https://static-01.daraz.com.np/p/284f3119fd81a6fc1a45b34f1aa29841.jpg",
        "itemHaveStock": 1,
        "price": "248",
        "currency": "Rs.",
        "itemPrice": "549",
        },
      {
        "isCurrencyLeft": 1,
        "title": "Vintage T-9 Hair Trimmer For Men Plastic Body",
        "itemSoldCnt": 9,
        "itemDiscount": "63%",
        "itemCurrentStock": 6,
        "itemId": 179143900,
        "image": "https://static-01.daraz.com.np/p/9aa012720024aef1d31d0960eecf6fd5.jpg",
        "itemHaveStock": 1,
        "price": "299",
        "currency": "Rs.",
        "itemPrice": "800",
        },
]